import type {
  StintData,
  DetailedBalances,
  AccountBalances,
  FundHolding,
  HoldingsAccountKey,
  FixedAccountKey,
  CustomAccount,
} from './types';
import {
  HOLDINGS_ENABLED_KEYS,
  holdingMarketValue,
  holdingsTotal,
  holdingsCostBasisTotal,
  effectiveBalance,
} from './types';
import type { ExpenseModel, RecurringExpense, OneTimeExpense } from '../hooks/useExpenseModel';
import type { PlannerSettings } from '../hooks/usePlannerSettings';
import type { RetirementSettings } from '../hooks/useRetirementSettings';
import type { SavedScenario } from '../hooks/useSavedScenarios';
import { estimateTaxes, estimateW2Taxes } from './tax';
import { weekdaysElapsedYTD, currentYear, monthName } from './helpers';

export interface BriefingInput {
  data: StintData;
  detailed: DetailedBalances;
  balances: AccountBalances;
  expenseModel: ExpenseModel;
  planner: PlannerSettings;
  retirement: RetirementSettings;
  scenarios: SavedScenario[];
  profileText: string;
  questionsText: string;
}

// Markdown-friendly currency: plain ASCII for LLM consumption.
function m$(n: number): string {
  const rounded = Math.round(n);
  const sign = rounded < 0 ? '-' : '';
  return `${sign}$${Math.abs(rounded).toLocaleString('en-US')}`;
}

function mPct(n: number, decimals = 1): string {
  return `${(n * 100).toFixed(decimals)}%`;
}

function mTable(headers: string[], rows: string[][]): string {
  const head = `| ${headers.join(' | ')} |`;
  const sep = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map((r) => `| ${r.join(' | ')} |`).join('\n');
  return `${head}\n${sep}\n${body}`;
}

const EXPENSE_RATIOS: Record<string, number> = {
  AEPGX: 0.0082,
  ANEFX: 0.0075,
  DODBX: 0.0052,
  SPY: 0.0009,
};

const ESSENTIAL_CATEGORIES = new Set(['housing', 'insurance', 'utilities', 'food', 'transport', 'health']);

function classifyExpense(e: RecurringExpense): 'essential' | 'discretionary' {
  return ESSENTIAL_CATEGORIES.has(e.category) ? 'essential' : 'discretionary';
}

const HOLDINGS_LABEL: Record<HoldingsAccountKey, string> = {
  nonRetirement: 'Brokerage (Non-retirement)',
  traditionalIRA: 'Traditional IRA',
  rolloverIRA: 'Rollover IRA',
};

const ACCOUNT_GROUPS: { heading: string; entries: { key: FixedAccountKey; label: string; type: 'asset' | 'debt' }[] }[] = [
  {
    heading: 'Cash & Checking',
    entries: [
      { key: 'advRelationship', label: 'Adv Relationship Banking', type: 'asset' },
      { key: 'santanderChecking', label: 'Santander Private Client Checking', type: 'asset' },
      { key: 'advantageSavings', label: 'Advantage Savings', type: 'asset' },
    ],
  },
  {
    heading: 'Savings',
    entries: [
      { key: 'highYieldSavings', label: 'High Yield Savings', type: 'asset' },
      { key: 'openbankHYS', label: 'Openbank High Yield Savings', type: 'asset' },
      { key: 'santanderMM', label: 'Santander Private Client Money Market', type: 'asset' },
    ],
  },
  {
    heading: 'Investments — Non-retirement',
    entries: [
      { key: 'nonRetirement', label: 'Non-retirement Brokerage', type: 'asset' },
    ],
  },
  {
    heading: 'Investments — Retirement',
    entries: [
      { key: 'traditionalIRA', label: 'Traditional IRA', type: 'asset' },
      { key: 'rolloverIRA', label: 'Rollover IRA', type: 'asset' },
    ],
  },
  {
    heading: 'Other Investments',
    entries: [
      { key: 'hsa', label: 'Health Savings Account', type: 'asset' },
    ],
  },
  {
    heading: 'Credit',
    entries: [
      { key: 'citiDoubleCash', label: 'Citi Double Cash Card', type: 'debt' },
    ],
  },
];

function balanceFor(d: DetailedBalances, key: FixedAccountKey): number {
  if (HOLDINGS_ENABLED_KEYS.includes(key as HoldingsAccountKey)) {
    return effectiveBalance(d, key as HoldingsAccountKey);
  }
  return d[key] as number;
}

export function buildBriefing(input: BriefingInput): string {
  const today = new Date();
  const todayStr = today.toISOString().slice(0, 10);

  const sections: string[] = [];
  sections.push(`# Financial Briefing — ${todayStr}\n\n*Generated by Stint Ledger for analysis by Claude.*`);
  sections.push(buildProfile(input));
  sections.push(buildFinancialPosition(input));
  sections.push(buildHoldings(input));
  sections.push(buildIncomeWork(input));
  sections.push(buildInvoiceStatus(input));
  sections.push(buildExpenses(input));
  sections.push(buildCashFlow(input));
  sections.push(buildProjections(input));
  sections.push(buildRetirement(input));
  sections.push(buildSavedScenarios(input));
  sections.push(buildQuestions(input));

  return sections.join('\n\n---\n\n') + '\n';
}

// ─── Section 1: Profile ────────────────────────────────────────────────────────

function buildProfile({ profileText }: BriefingInput): string {
  return `## 1. Profile\n\n${profileText.trim()}`;
}

// ─── Section 2: Financial Position ─────────────────────────────────────────────

function activeMonthlyExpenses(input: BriefingInput): number {
  const recurring = input.expenseModel.recurring.filter((e) => !e.muted).reduce((s, e) => s + e.amount, 0);
  const mode = input.planner.employmentMode ?? 'freelance';
  const base = recurring > 0
    ? recurring
    : (mode === 'fulltime' ? input.planner.monthlyExpensesFullTime : input.planner.monthlyExpensesFreelance);
  const health = mode === 'fulltime' ? (input.planner.ftHealthIns ?? 300) : input.planner.healthIns;
  return base + health;
}

function buildFinancialPosition(input: BriefingInput): string {
  const { detailed, balances } = input;
  const muted = new Set(detailed.mutedAccounts ?? []);
  const out: string[] = ['## 2. Financial Position'];

  // Totals (mute-aware: balances already excludes muted; we use balances here)
  const totalNW =
    balances.checking + balances.hys + balances.moneyMarket +
    balances.brokerage + balances.tradIRA + balances.rolloverIRA +
    balances.hsa + balances.ccDebt;
  const accessibleNW = balances.checking + balances.hys + balances.moneyMarket + balances.brokerage + balances.ccDebt;
  const retirementNW = balances.tradIRA + balances.rolloverIRA + balances.hsa;

  out.push(`**Total Net Worth:** ${m$(totalNW)}`);
  out.push(`**Accessible Net Worth:** ${m$(accessibleNW)}  *(checking + savings + brokerage − debt)*`);
  out.push(`**Retirement Net Worth:** ${m$(retirementNW)}`);

  // Account breakdown
  out.push(`\n### Account Breakdown\n`);
  for (const group of ACCOUNT_GROUPS) {
    const rows: string[][] = [];
    let subtotal = 0;
    for (const entry of group.entries) {
      const bal = balanceFor(detailed, entry.key);
      const isMuted = muted.has(entry.key);
      const balStr = m$(bal);
      const label = isMuted ? `${entry.label} *(muted)*` : entry.label;
      if (!isMuted) subtotal += bal;
      rows.push([label, balStr]);
    }
    // Custom accounts for this group's section — append by matching group heading loosely.
    out.push(`**${group.heading}:** ${m$(subtotal)}`);
    out.push(mTable(['Account', 'Balance'], rows));
    out.push('');
  }

  // Custom accounts (all sections together for simplicity)
  const customs: CustomAccount[] = detailed.customAccounts ?? [];
  if (customs.length > 0) {
    out.push(`### Custom Accounts\n`);
    const rows = customs.map((a) => {
      const isMuted = muted.has(a.id);
      const label = isMuted ? `${a.name} *(muted)*` : a.name;
      return [label, a.type, m$(a.balance)];
    });
    out.push(mTable(['Account', 'Type', 'Balance'], rows));
  }

  // Allocation percentages — assets only
  const totalAssets =
    Math.max(0, balances.checking) +
    Math.max(0, balances.hys) +
    Math.max(0, balances.moneyMarket) +
    Math.max(0, balances.brokerage) +
    Math.max(0, balances.tradIRA) +
    Math.max(0, balances.rolloverIRA) +
    Math.max(0, balances.hsa);

  const alloc = [
    { label: 'Cash & Checking', value: balances.checking },
    { label: 'Savings (HYS + MM)', value: balances.hys + balances.moneyMarket },
    { label: 'Brokerage', value: balances.brokerage },
    { label: 'Traditional IRA', value: balances.tradIRA },
    { label: 'Rollover IRA', value: balances.rolloverIRA },
    { label: 'HSA', value: balances.hsa },
  ].filter((a) => a.value > 0);

  out.push(`\n### Asset Allocation\n`);
  out.push(mTable(
    ['Category', 'Value', '% of Assets'],
    alloc.map((a) => [a.label, m$(a.value), totalAssets > 0 ? mPct(a.value / totalAssets, 1) : '0.0%']),
  ));

  // Debt summary
  out.push(`\n### Debt\n`);
  if (balances.ccDebt < 0) {
    out.push(`- Credit card balance: ${m$(Math.abs(balances.ccDebt))} (Citi Double Cash)`);
  } else {
    out.push(`- No credit card debt.`);
  }

  // Liquid runway + FI progress
  const monthlyExpenses = activeMonthlyExpenses(input);
  const liquidAssets = balances.checking + balances.hys + balances.moneyMarket;
  const runwayMonths = monthlyExpenses > 0 ? liquidAssets / monthlyExpenses : 0;
  const annualExpenses = monthlyExpenses * 12;
  const fiTarget = annualExpenses * 25;
  const totalNWForFi =
    balances.checking + balances.hys + balances.moneyMarket +
    balances.brokerage + balances.tradIRA + balances.rolloverIRA +
    balances.hsa + balances.ccDebt;
  const fiProgress = fiTarget > 0 ? totalNWForFi / fiTarget : 0;

  out.push(`\n### Liquid Runway & FI Progress\n`);
  out.push(`- **Liquid runway:** ${runwayMonths.toFixed(1)} months *(liquid assets ${m$(liquidAssets)} ÷ monthly expenses ${m$(monthlyExpenses)})*`);
  out.push(`- **FI progress:** ${mPct(fiProgress, 1)} of ${m$(fiTarget)} target *(25× annual expenses of ${m$(annualExpenses)})*`);

  return out.join('\n');
}

// ─── Section 3: Investment Holdings ────────────────────────────────────────────

function buildHoldings({ detailed }: BriefingInput): string {
  const out: string[] = ['## 3. Investment Holdings'];

  let portfolioMV = 0;
  const allHoldings: { ticker: string; mv: number; accountLabel: string }[] = [];

  for (const key of HOLDINGS_ENABLED_KEYS) {
    const list = detailed.holdings?.[key] ?? [];
    if (list.length === 0) continue;
    const total = holdingsTotal(list);
    const costTotal = holdingsCostBasisTotal(list);
    const accountGL = total - costTotal;
    const accountGLPct = costTotal > 0 ? accountGL / costTotal : 0;

    out.push(`\n### ${HOLDINGS_LABEL[key]}\n`);

    const rows = list.map((h: FundHolding) => {
      const mv = holdingMarketValue(h);
      const gl = mv - h.costBasis;
      const glPct = h.costBasis > 0 ? gl / h.costBasis : 0;
      const expense = EXPENSE_RATIOS[h.ticker.toUpperCase()];
      const expStr = expense !== undefined ? mPct(expense, 2) : '—';
      portfolioMV += mv;
      allHoldings.push({ ticker: h.ticker, mv, accountLabel: HOLDINGS_LABEL[key] });
      return [
        h.ticker,
        h.name,
        h.shares.toLocaleString('en-US', { maximumFractionDigits: 3 }),
        m$(mv),
        m$(h.costBasis),
        `${gl >= 0 ? '+' : ''}${m$(gl)}`,
        `${gl >= 0 ? '+' : ''}${mPct(glPct, 1)}`,
        expStr,
      ];
    });

    out.push(mTable(
      ['Ticker', 'Name', 'Shares', 'Mkt Value', 'Cost Basis', 'G/L', 'G/L %', 'Expense Ratio'],
      rows,
    ));
    out.push(`\n**Account total:** ${m$(total)} • **Cost basis:** ${m$(costTotal)} • **Unrealized G/L:** ${accountGL >= 0 ? '+' : ''}${m$(accountGL)} (${accountGL >= 0 ? '+' : ''}${mPct(accountGLPct, 2)})`);
  }

  // Overall portfolio allocation by ticker
  if (allHoldings.length > 0 && portfolioMV > 0) {
    const byTicker = new Map<string, number>();
    for (const h of allHoldings) {
      byTicker.set(h.ticker, (byTicker.get(h.ticker) ?? 0) + h.mv);
    }
    const allocRows = Array.from(byTicker.entries())
      .sort((a, b) => b[1] - a[1])
      .map(([ticker, value]) => [ticker, m$(value), mPct(value / portfolioMV, 1)]);

    out.push(`\n### Portfolio Allocation by Fund\n`);
    out.push(mTable(['Ticker', 'Value', '% of Portfolio'], allocRows));
    out.push(`\n**Total portfolio market value:** ${m$(portfolioMV)}`);
  }

  return out.join('\n');
}

// ─── Section 4: Income & Work ──────────────────────────────────────────────────

function buildIncomeWork({ data }: BriefingInput): string {
  const year = currentYear();
  const yearStr = String(year);
  const out: string[] = [`## 4. Income & Work (${year} YTD)`];

  const yearEntries = data.timeEntries.filter((e) => e.date.startsWith(yearStr));
  const ytdIncome = yearEntries.reduce((s, e) => s + e.amount, 0);

  const dayRateDates = new Set(
    yearEntries.filter((e) => e.service_type === 'day_rate').map((e) => e.date),
  );
  const daysWorked = dayRateDates.size;
  const weekdaysElapsed = weekdaysElapsedYTD(year);
  const utilization = weekdaysElapsed > 0 ? daysWorked / weekdaysElapsed : 0;
  const dayRateEntries = yearEntries.filter((e) => e.service_type === 'day_rate');
  const avgDayRate = daysWorked > 0
    ? dayRateEntries.reduce((s, e) => s + e.amount, 0) / daysWorked
    : 0;
  const currentDayRate = data.settings?.service_rates?.day_rate ?? 1200;

  out.push(`- **YTD income:** ${m$(ytdIncome)}`);
  out.push(`- **Days worked:** ${daysWorked} of ${weekdaysElapsed} weekdays elapsed`);
  out.push(`- **YTD utilization:** ${mPct(utilization, 1)}`);
  out.push(`- **Average day rate (actual):** ${m$(avgDayRate)}`);
  out.push(`- **Current configured day rate:** ${m$(currentDayRate)}`);

  // Monthly income breakdown
  const monthly: number[] = Array(12).fill(0);
  yearEntries.forEach((e) => {
    const m = parseInt(e.date.substring(5, 7), 10) - 1;
    monthly[m] += e.amount;
  });
  const currentMonth = new Date().getMonth();
  out.push(`\n### Monthly Income (${year})\n`);
  const monthlyRows = monthly
    .map((v, i) => [monthName(i), m$(v)])
    .filter((_, i) => i <= currentMonth);
  out.push(mTable(['Month', 'Income'], monthlyRows));

  // Income by client
  const clientMap = new Map<string, string>();
  data.clients.forEach((c) => clientMap.set(c.id, c.name));
  const projectMap = new Map<string, string>();
  data.projects.forEach((p) => projectMap.set(p.id, p.client_id));

  const byClient = new Map<string, number>();
  for (const e of yearEntries) {
    const clientId = projectMap.get(e.project_id) ?? 'unknown';
    byClient.set(clientId, (byClient.get(clientId) ?? 0) + e.amount);
  }
  if (byClient.size > 0 && ytdIncome > 0) {
    const rows = Array.from(byClient.entries())
      .sort((a, b) => b[1] - a[1])
      .map(([cid, amt]) => [clientMap.get(cid) ?? 'Unknown', m$(amt), mPct(amt / ytdIncome, 1)]);
    out.push(`\n### Income by Client\n`);
    out.push(mTable(['Client', 'Amount', '% of YTD'], rows));
  }

  // Pipeline
  const todayStr = new Date().toISOString().slice(0, 10);
  const PRIORITY_WEIGHTS = [1.0, 0.7, 0.4, 0.2];
  const defaultRate = data.settings?.service_rates?.day_rate ?? currentDayRate;
  const clientRate = (clientId: string | null | undefined): number => {
    if (!clientId) return defaultRate;
    const c = data.clients.find((cl) => cl.id === clientId);
    return c?.service_rates?.day_rate ?? defaultRate;
  };
  const weekdaysBetween = (s: string, e: string): number => {
    const start = new Date(s + 'T00:00:00');
    const end = new Date(e + 'T00:00:00');
    let count = 0;
    const d = new Date(start);
    while (d <= end) {
      const day = d.getDay();
      if (day !== 0 && day !== 6) count++;
      d.setDate(d.getDate() + 1);
    }
    return count;
  };
  let bookedDays = 0;
  let penciledDays = 0;
  let weightedValue = 0;
  for (const p of data.pencils) {
    if (p.end_date < todayStr) continue;
    const days = weekdaysBetween(p.start_date, p.end_date);
    const proj = data.projects.find((pr) => pr.id === p.project_id);
    const cid = proj?.client_id ?? p.client_id ?? null;
    const rate = clientRate(cid);
    const value = days * rate;
    const weight = PRIORITY_WEIGHTS[p.priority] ?? 0.2;
    if (p.priority === 0) bookedDays += days;
    else penciledDays += days;
    weightedValue += value * weight;
  }
  out.push(`\n### Pipeline Ahead\n`);
  out.push(`- **Booked days:** ${bookedDays}`);
  out.push(`- **Penciled days:** ${penciledDays}`);
  out.push(`- **Weighted pipeline value:** ${m$(weightedValue)} *(booked 100% + pencil 70%/40%/20% by priority)*`);

  return out.join('\n');
}

// ─── Section 5: Invoice Status ─────────────────────────────────────────────────

function buildInvoiceStatus({ data }: BriefingInput): string {
  const year = currentYear();
  const yearStr = String(year);
  const out: string[] = ['## 5. Invoice Status'];

  const byStatus = new Map<string, { count: number; total: number }>();
  for (const inv of data.invoices) {
    const cur = byStatus.get(inv.status) ?? { count: 0, total: 0 };
    cur.count += 1;
    cur.total += inv.total;
    byStatus.set(inv.status, cur);
  }

  const outstanding = (byStatus.get('sent')?.total ?? 0) + (byStatus.get('overdue')?.total ?? 0);
  const overdue = byStatus.get('overdue')?.total ?? 0;
  const awaiting = byStatus.get('sent')?.total ?? 0;

  // Paid YTD
  const paidYTD = data.invoices
    .filter((i) => i.status === 'paid' && (i.issue_date?.startsWith(yearStr) ?? false))
    .reduce((s, i) => s + i.total, 0);

  out.push(`- **Outstanding:** ${m$(outstanding)} (sent + overdue)`);
  out.push(`- **Overdue:** ${m$(overdue)}`);
  out.push(`- **Awaiting payment:** ${m$(awaiting)}`);
  out.push(`- **Paid YTD:** ${m$(paidYTD)}`);

  if (byStatus.size > 0) {
    out.push(`\n### By Status\n`);
    const rows = Array.from(byStatus.entries()).map(([st, v]) => [st, String(v.count), m$(v.total)]);
    out.push(mTable(['Status', 'Count', 'Total'], rows));
  }

  return out.join('\n');
}

// ─── Section 6: Expenses ───────────────────────────────────────────────────────

function buildExpenses({ expenseModel, planner }: BriefingInput): string {
  const out: string[] = ['## 6. Expenses'];

  const active = expenseModel.recurring.filter((e) => !e.muted);
  const muted = expenseModel.recurring.filter((e) => e.muted);

  const essentialTotal = active.filter((e) => classifyExpense(e) === 'essential').reduce((s, e) => s + e.amount, 0);
  const discretionaryTotal = active.filter((e) => classifyExpense(e) === 'discretionary').reduce((s, e) => s + e.amount, 0);
  const recurringTotal = essentialTotal + discretionaryTotal;

  out.push(`- **Monthly recurring total (active):** ${m$(recurringTotal)}`);
  out.push(`  - Essential: ${m$(essentialTotal)}`);
  out.push(`  - Discretionary: ${m$(discretionaryTotal)}`);
  out.push(`- **Health insurance (planner setting, separate):** ${m$(planner.healthIns)} freelance / ${m$(planner.ftHealthIns ?? 0)} full-time`);
  out.push(`- **Annual recurring total:** ${m$(recurringTotal * 12)}`);

  out.push(`\n### Recurring Expenses\n`);
  const recurringRows = expenseModel.recurring.map((e: RecurringExpense) => [
    e.muted ? `${e.name} *(muted)*` : e.name,
    m$(e.amount),
    e.category,
    classifyExpense(e),
    e.muted ? 'muted' : 'active',
  ]);
  out.push(mTable(['Name', 'Monthly', 'Category', 'Classification', 'Status'], recurringRows));

  const upcomingOneTime = expenseModel.oneTime.filter((e) => !e.muted);
  if (upcomingOneTime.length > 0) {
    const oneTimeTotal = upcomingOneTime.reduce((s, e) => s + e.amount, 0);
    out.push(`\n### One-time Expenses Planned\n`);
    const otRows = upcomingOneTime.map((e: OneTimeExpense) => [e.name, m$(e.amount), monthName(e.month)]);
    out.push(mTable(['Name', 'Amount', 'Month'], otRows));
    out.push(`\n**One-time total:** ${m$(oneTimeTotal)}`);
  }

  if (muted.length > 0) {
    out.push(`\n*${muted.length} recurring expense(s) currently muted, excluded from totals above.*`);
  }

  return out.join('\n');
}

// ─── Section 7: Cash Flow ──────────────────────────────────────────────────────

interface CashFlowComputed {
  mode: 'freelance' | 'fulltime';
  grossAnnual: number;
  netAnnual: number;
  taxesAnnual: number;
  effectiveTaxRate: number;
  monthlyExpenses: number;
  monthlyInterest: number;
  monthlyInvestmentReturns: number;
  monthlyCashFlow: number;
  annualSavings: number;
  fullAnnualSavings: number;
  annualRetirementGrowth: number;
}

function computeCashFlow({ planner, balances, expenseModel }: BriefingInput): CashFlowComputed {
  const mode = planner.employmentMode ?? 'freelance';
  const recurring = expenseModel.recurring.filter((e) => !e.muted).reduce((s, e) => s + e.amount, 0);
  const monthlyExpensesBase = recurring > 0 ? recurring : (mode === 'fulltime' ? planner.monthlyExpensesFullTime : planner.monthlyExpensesFreelance);
  const healthIns = mode === 'fulltime' ? (planner.ftHealthIns ?? 300) : planner.healthIns;
  const monthlyExpenses = monthlyExpensesBase + healthIns;

  const monthlyInterest = (balances.hys * planner.cashReturn + balances.moneyMarket * planner.cashReturn) / 12;
  const monthlyInvestmentReturns = balances.brokerage * planner.equityReturn / 12;

  const annualRetirementGrowth =
    balances.tradIRA * planner.equityReturn +
    balances.rolloverIRA * planner.rolloverReturn +
    balances.hsa * planner.equityReturn;

  if (mode === 'fulltime') {
    const salary = planner.ftSalary ?? 180000;
    const contrib401k = planner.ftContribution401k ?? 23500;
    const taxes = estimateW2Taxes(salary, contrib401k);
    const monthlyCashFlow = taxes.netMonthly + (planner.fullFinancialPicture ? monthlyInterest + monthlyInvestmentReturns : 0) - monthlyExpenses;
    const fullMonthlyCashFlow = taxes.netMonthly + monthlyInterest + monthlyInvestmentReturns - monthlyExpenses;
    return {
      mode,
      grossAnnual: salary,
      netAnnual: taxes.netAnnual,
      taxesAnnual: taxes.totalTax,
      effectiveTaxRate: taxes.effectiveRate,
      monthlyExpenses,
      monthlyInterest,
      monthlyInvestmentReturns,
      monthlyCashFlow,
      annualSavings: monthlyCashFlow * 12,
      fullAnnualSavings: fullMonthlyCashFlow * 12,
      annualRetirementGrowth,
    };
  }

  // Freelance
  const availableDays = 260 - planner.vacationDays - planner.holidays - planner.sickDays;
  const grossAnnual = planner.dayRate * availableDays * planner.utilization;
  const taxes = estimateTaxes(grossAnnual);
  const freelanceMonthlyCashFlow = taxes.netMonthly - monthlyExpenses;
  const fullMonthlyCashFlow = freelanceMonthlyCashFlow + monthlyInterest + monthlyInvestmentReturns;
  const monthlyCashFlow = planner.fullFinancialPicture ? fullMonthlyCashFlow : freelanceMonthlyCashFlow;
  return {
    mode,
    grossAnnual,
    netAnnual: taxes.netAnnual,
    taxesAnnual: taxes.totalTax,
    effectiveTaxRate: taxes.effectiveRate,
    monthlyExpenses,
    monthlyInterest,
    monthlyInvestmentReturns,
    monthlyCashFlow,
    annualSavings: monthlyCashFlow * 12,
    fullAnnualSavings: fullMonthlyCashFlow * 12,
    annualRetirementGrowth,
  };
}

function buildCashFlow(input: BriefingInput): string {
  const c = computeCashFlow(input);
  const { planner } = input;
  const availableDays = 260 - planner.vacationDays - planner.holidays - planner.sickDays;
  const out: string[] = ['## 7. Cash Flow (Planner Scenario)'];

  out.push(`**Mode:** ${c.mode === 'freelance' ? 'Freelance' : 'Full-time'}`);

  if (c.mode === 'freelance') {
    out.push(`- Day rate: ${m$(planner.dayRate)}`);
    out.push(`- Utilization: ${mPct(planner.utilization, 0)}`);
    out.push(`- Available days/year: ${availableDays} (260 − ${planner.vacationDays} vacation − ${planner.holidays} holidays − ${planner.sickDays} sick)`);
    out.push(`- Gross annual: ${m$(c.grossAnnual)}`);
    out.push(`- Taxes (SE + Fed + NY State): ${m$(c.taxesAnnual)} (effective ${mPct(c.effectiveTaxRate, 1)})`);
    out.push(`- Net annual: ${m$(c.netAnnual)}`);
  } else {
    out.push(`- Salary: ${m$(planner.ftSalary ?? 180000)}`);
    out.push(`- 401k contribution: ${m$(planner.ftContribution401k ?? 23500)}`);
    out.push(`- Employer match: ${mPct(planner.ftEmployerMatch ?? 0.04, 1)} of salary = ${m$((planner.ftSalary ?? 180000) * (planner.ftEmployerMatch ?? 0.04))}`);
    out.push(`- Taxes (FICA + Fed + NY State): ${m$(c.taxesAnnual)} (effective ${mPct(c.effectiveTaxRate, 1)})`);
    out.push(`- Net annual: ${m$(c.netAnnual)}`);
  }

  out.push(`\n### Monthly Breakdown (Active toggle: ${planner.fullFinancialPicture ? 'full picture' : 'income only'})\n`);
  const incomeMonthly = c.netAnnual / 12;
  const monthlyBreakdown = mTable(
    ['Line', 'Monthly'],
    [
      ['Net income (after taxes)', m$(incomeMonthly)],
      ['Interest income (HYS + MM)', m$(c.monthlyInterest)],
      ['Investment returns (brokerage)', m$(c.monthlyInvestmentReturns)],
      ['Total expenses (recurring + health)', m$(-c.monthlyExpenses)],
      ['**Net monthly cash flow**', `**${m$(c.monthlyCashFlow)}**`],
    ],
  );
  out.push(monthlyBreakdown);

  out.push(`\n- **Annual savings (active toggle):** ${m$(c.annualSavings)}`);
  out.push(`- **Annual savings (full picture):** ${m$(c.fullAnnualSavings)}`);
  out.push(`- **Annual retirement account growth (nominal):** ${m$(c.annualRetirementGrowth)}`);

  return out.join('\n');
}

// ─── Section 8: Projections ────────────────────────────────────────────────────

function buildProjections(input: BriefingInput): string {
  const { planner, balances } = input;
  const out: string[] = ['## 8. Projections'];

  const c = computeCashFlow(input);
  const realCashReturn = planner.cashReturn - planner.inflationRate;
  const realEquityReturn = planner.equityReturn - planner.inflationRate;
  const realRolloverReturn = planner.rolloverReturn - planner.inflationRate;

  out.push(`### 5-Year Net Worth Projection (real, after ${mPct(planner.inflationRate, 1)} inflation)\n`);

  let checking = balances.checking;
  let hys = balances.hys;
  let mm = balances.moneyMarket;
  let brokerage = balances.brokerage;
  const debt = balances.ccDebt;
  let tradIRA = balances.tradIRA;
  let rolloverIRA = balances.rolloverIRA;
  let hsa = balances.hsa;

  const year = currentYear();
  const rows: string[][] = [];
  for (let y = 0; y <= 5; y++) {
    const accessible = checking + hys + mm + brokerage + debt;
    const retirement = tradIRA + rolloverIRA + hsa;
    rows.push([
      String(year + y),
      m$(accessible),
      m$(retirement),
      m$(accessible + retirement),
    ]);
    if (y < 5) {
      hys *= (1 + realCashReturn);
      mm *= (1 + realCashReturn);
      brokerage *= (1 + realEquityReturn);
      tradIRA *= (1 + realEquityReturn);
      rolloverIRA *= (1 + realRolloverReturn);
      hsa *= (1 + realEquityReturn);
      if (planner.employmentMode === 'fulltime') {
        const salary = planner.ftSalary ?? 180000;
        const contrib401k = planner.ftContribution401k ?? 23500;
        const match = salary * (planner.ftEmployerMatch ?? 0.04);
        tradIRA += contrib401k + match;
        checking += c.fullAnnualSavings;
      } else {
        checking += c.fullAnnualSavings;
      }
    }
  }
  out.push(mTable(['Year', 'Accessible', 'Retirement', 'Total NW'], rows));

  out.push(`\n### Return Assumptions\n`);
  out.push(mTable(
    ['Asset class', 'Nominal', 'Real (after inflation)'],
    [
      ['Equity (brokerage, TradIRA, HSA)', mPct(planner.equityReturn, 1), mPct(realEquityReturn, 1)],
      ['Rollover IRA (SPY)', mPct(planner.rolloverReturn, 1), mPct(realRolloverReturn, 1)],
      ['Cash (HYS, MM)', mPct(planner.cashReturn, 1), mPct(realCashReturn, 1)],
      ['Inflation', mPct(planner.inflationRate, 1), '—'],
    ],
  ));

  out.push(`\n*Rollover IRA is currently deployed in SPY (S&P 500 ETF). Rollover return defaults to the equity rate.*`);

  return out.join('\n');
}

// ─── Section 9: Retirement ─────────────────────────────────────────────────────

function buildRetirement({ retirement, planner, balances }: BriefingInput): string {
  const out: string[] = ['## 9. Retirement'];

  const realPreReturn = retirement.preReturnRate - retirement.inflationRate;
  const realRetReturn = retirement.retReturnRate - retirement.inflationRate;

  const retirementBalance = balances.tradIRA + balances.rolloverIRA + balances.hsa;
  let retBal = retirementBalance;
  let taxBal = retirement.includeTaxable ? balances.brokerage : 0;
  const annualWithdrawal = (retirement.monthlySpending * 12) - (retirement.socialSecurity * 12);

  let balanceAtRetirement = 0;
  let depletionAge: number | null = null;

  const empMode = planner.employmentMode ?? 'freelance';

  for (let age = retirement.currentAge; age <= 95; age++) {
    if (age === retirement.retirementAge) balanceAtRetirement = retBal + taxBal;
    const total = retBal + taxBal;
    if (age < retirement.retirementAge) {
      const annual401k = empMode === 'fulltime'
        ? (planner.ftContribution401k ?? 23500) + (planner.ftSalary ?? 180000) * (planner.ftEmployerMatch ?? 0.04)
        : 0;
      retBal = retBal * (1 + realPreReturn) + retirement.annualIRAContribution + retirement.annualHSAContribution + annual401k;
      taxBal = taxBal * (1 + realPreReturn);
    } else {
      const retGrown = retBal * (1 + realRetReturn);
      const taxGrown = taxBal * (1 + realRetReturn);
      const totalGrown = retGrown + taxGrown;
      const afterWithdraw = totalGrown - annualWithdrawal;
      if (afterWithdraw <= 0) {
        if (depletionAge === null && total > 0) depletionAge = age + 1;
        retBal = 0;
        taxBal = 0;
      } else {
        const ratio = afterWithdraw / totalGrown;
        retBal = retGrown * ratio;
        taxBal = taxGrown * ratio;
      }
    }
  }
  const yearsPortfolioLasts = depletionAge !== null
    ? depletionAge - retirement.retirementAge
    : 95 - retirement.retirementAge;
  const safeWithdrawalRate = balanceAtRetirement > 0 ? annualWithdrawal / balanceAtRetirement : 0;

  out.push(`### Current Settings\n`);
  out.push(`- Current age: ${retirement.currentAge}`);
  out.push(`- Target retirement age: ${retirement.retirementAge} (${retirement.retirementAge - retirement.currentAge} years away)`);
  out.push(`- Annual IRA contribution: ${m$(retirement.annualIRAContribution)}`);
  out.push(`- Annual HSA contribution: ${m$(retirement.annualHSAContribution)}`);
  out.push(`- Pre-retirement return: ${mPct(retirement.preReturnRate, 1)} nominal, ${mPct(realPreReturn, 1)} real`);
  out.push(`- Retirement-phase return: ${mPct(retirement.retReturnRate, 1)} nominal, ${mPct(realRetReturn, 1)} real`);
  out.push(`- Inflation: ${mPct(retirement.inflationRate, 1)}`);
  out.push(`- Monthly spending in retirement: ${m$(retirement.monthlySpending)} (${m$(retirement.monthlySpending * 12)}/yr)`);
  out.push(`- Monthly Social Security assumed: ${m$(retirement.socialSecurity)}`);
  out.push(`- Includes taxable brokerage in projection: ${retirement.includeTaxable ? 'yes' : 'no'}`);

  out.push(`\n### Projection Outputs\n`);
  out.push(`- **Projected balance at retirement (today's dollars):** ${m$(balanceAtRetirement)}`);
  out.push(`- **Years portfolio lasts:** ${yearsPortfolioLasts}${depletionAge !== null ? ` (depleted at age ${depletionAge})` : ' (no depletion by age 95)'}`);
  out.push(`- **Implied safe withdrawal rate:** ${mPct(safeWithdrawalRate, 2)}`);

  return out.join('\n');
}

// ─── Section 10: Saved Scenarios ───────────────────────────────────────────────

function buildSavedScenarios({ scenarios }: BriefingInput): string {
  const out: string[] = ['## 10. Saved Scenarios'];

  if (scenarios.length === 0) {
    out.push(`\n*No saved scenarios.*`);
    return out.join('\n');
  }

  const rows = scenarios.map((s: SavedScenario) => [
    s.name,
    s.metrics.mode,
    m$(s.metrics.grossAnnual),
    m$(s.metrics.netAnnual),
    m$(s.metrics.monthlyCashFlowFull),
    m$(s.metrics.annualSavingsFull),
    m$(s.metrics.monthlyExpenses),
    m$(s.metrics.year5NetWorth),
  ]);
  out.push(mTable(
    ['Name', 'Mode', 'Gross', 'Net', 'Monthly CF (full)', 'Annual Savings', 'Monthly Expenses', 'Year-5 NW'],
    rows,
  ));

  return out.join('\n');
}

// ─── Section 11: Questions & Focus Areas ───────────────────────────────────────

function buildQuestions({ questionsText }: BriefingInput): string {
  return `## 11. Questions & Focus Areas\n\n${questionsText.trim()}`;
}
